language: node_js
node_js:
    - 6
    - 5
    - 4
script:
    - npm run build
    - npm run lint
    - nyc --silent npm run test
    - nyc report --reporter=text-lcov | coveralls -v
    - nyc check-coverage --lines 90
notifications:
    email: false
sudo: false
