language: node_js
node_js:
    - 6
    - 5
    - 4
cache:
  directories:
    - node_modules
before_install:
    - npm install --global npm@3
script:
    - export NODE_ENV=development
    - npm run build
    - npm run lint
    - flow
    - nyc --silent npm run test
    - nyc report --reporter=text-lcov | coveralls
    - nyc check-coverage --lines 90
    - conventional-changelog-lint --from=HEAD~$(git --no-pager rev-list master..HEAD --count)
after_success:
    - git config --global user.name "semantic-release (via TravisCI)"
    - git config --global user.email "semantic-release@travis"
    - 'semantic-release pre && (npm run documentation && git commit -m "docs: update documentation" ./README.md && git push) && (NODE_ENV=production npm run build) && npm publish && semantic-release post'
notifications:
    email: false
sudo: false
