language: node_js
node_js:
    - 6
    - 5
    - 4
cache:
  directories:
    - node_modules
before_install:
    - npm install --global npm@3
script:
    - npm run build
    - npm run lint
    - nyc --silent npm run test
    - nyc report --reporter=text-lcov | coveralls
    - nyc check-coverage --lines 90
after_success:
    - git config --global user.name "semantic-release (via TravisCI)"
    - git config --global user.email "semantic-release@travis"
    - semantic-release pre && npm publish && semantic-release post
notifications:
    email: false
sudo: false
