language: node_js
node_js:
    - 6
    - 5
    - 4
before_install:
    - npm install --global npm@3
before_script:
    - curl -Lo travis_after_all.py https://git.io/vLSON
script:
    - NODE_ENV=development npm run build
    - rm -fr ./dist
    - NODE_ENV=production npm run build
    - npm run lint
    - flow
    - nyc --silent npm run test
    - nyc report --reporter=text-lcov | coveralls
    - nyc check-coverage --lines 90
    - conventional-changelog-lint --from=HEAD~$(git --no-pager rev-list master..HEAD --count)
after_success:
    - python travis_after_all.py
    - export $(cat .to_export_back)
    - git config --global user.name "semantic-release (via TravisCI)"
    - git config --global user.email "semantic-release@travis"
    - semantic-release pre && npm publish && semantic-release post
notifications:
    email: false
sudo: false
